pybo/views/answer_views.py
from datetime import datetime
from flask import Blueprint, render_template, url_for, request, g, flash
from werkzeug.utils import redirect
from pybo import db
from pybo.models import Question, Answer
from pybo.form import AnswerForm
from pybo.views.auth_views import login_required

bp = Blueprint('answer', __name__, url_prefix='/answer')


@bp.route('/create/<int:question_id>', methods=(['post']))
@login_required
def create(question_id):
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)
    if form.validate_on_submit():
        content = request.form['content']
        answer = Answer(question=question,
                        content=content,
                        create_day=datetime.now(),
                        user=g.user)
        db.session.add(answer)
        db.session.commit()
        return redirect(url_for('question.detail', question_id=question_id))
    return render_template('question/question_detail.html', question=question, form=form)


@bp.route('/modify/<int:answer_id>', methods=['GET', 'POST'])
@login_required
def modify(answer_id):
    answer = Answer.query.get_or_404(answer_id)
    if g.user != answer.user:
        flash('nope!')
        return redirect(url_for('question.detail', question_id=answer.question.id))
    if request.method == "POST":
        form = AnswerForm()
        if form.validate_on_submit():
            form.populate_obj(answer)
            answer.modify_date = datetime.now()
            db.session.commit()
            return redirect(url_for('question.detail', question_id=answer.question.id))
    else:
        form = AnswerForm(obj=answer)
    return render_template('answer/answer_form.html', answer=answer, form=form)


@bp.route('/delete/<int:answer_id>')
@login_required
def delete(answer_id):
    answer = Answer.query.get_or_404(answer_id)
    question_id = answer.question.id
    if g.user != answer.user:
        flash('nope')
    else:
        db.session.delete(answer)
        db.session.commit()
    return redirect(url_for('question.detail', question_id=question_id))

pybo/views/question_views.py
from datetime import datetime
from flask import Blueprint, render_template, request, url_for, g, flash
from werkzeug.utils import redirect
from pybo.models import Question
from pybo.form import QuestionForm, AnswerForm
from pybo import db
from pybo.views.auth_views import login_required

bp = Blueprint('question', __name__, url_prefix='/question')


@bp.route('/list')
def _list():
    page = request.args.get('page', type=int, default=1)
    question_list = Question.query.order_by(Question.create_day.desc())
    question_list = question_list.paginate(page, per_page=10)
    return render_template('question/question_list.html',
                           question_list=question_list)


@bp.route('/modify/<int:question_id>', methods=['GET', 'POST'])
@login_required
def modify(question_id):
    question = Question.query.get_or_404(question_id)
    if g.user != question.user:
        flash('no authority~')
        return redirect(url_for('question.detail', question_id=question_id))
    if request.method == 'POST':
        form = QuestionForm()
        if form.validate_on_submit():
            form.populate_obj(question)
            question.modify_date = datetime.now()
            db.session.commit()
            return redirect(url_for('question.detail', question_id=question_id))
    else:
        form = QuestionForm(obj=question)
    return render_template('question/question_form.html', form=form)


@bp.route('/detail/<int:question_id>/')
def detail(question_id):
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)
    return render_template('question/question_detail.html',
                           question=question,
                           form=form)

@bp.route('/delete/<int:question_id>')
@login_required
def delete(question_id):
    question = Question.query.get_or_404(question_id)
    if g.user != question.user :
        flash('no authority~')
        return redirect(url_for('question.detail', question_id=question_id))
    db.session.delete(question)
    db.session.commit()
    return redirect(url_for('question._list'))


@bp.route('/create', methods=('get', 'post'))
@login_required
def create():
    form = QuestionForm()
    if request.method == 'POST' and form.validate_on_submit():
        question = Question(subject=form.subject.data,
                            content=form.content.data,
                            create_day=datetime.now(),
                            user=g.user)
        db.session.add(question)
        db.session.commit()
        return redirect(url_for('main.index'))

    return render_template('question/question_form.html', form=form)

pybo/templates/question/question_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">

    <h2 class="border-bottom py-2">{{ question.subject }}</h2>

    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">
                {{ question.content }}
            </div>
            <div class="d-flex justify-content-end">
                {% if question.modify_date %}
                <div class="badge badge-light p-2 text-left mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ question.modify_date | datetime }}</div>
                </div>
                {% endif %}
                <div class="badge badge-light p-2 text-left">
                    <div class="mb-2">
                        {{ question.user.username }}
                    </div>
                    <div>
                        {{ question.create_day | datetime }}
                    </div>
                </div>
            </div>
            {% if g.user == question.user %}
            <div class="my-3">
                <a href="{{ url_for('question.modify', question_id=question.id) }}" class="btn btn-sm btn-outline-secondary">advise</a>
                <a href="#" class="delete btn btn-sm btn-outline-secondary" data-uri="{{ url_for('question.delete', question_id=question.id) }}">deeellettee</a>
            </div>
            {% endif %}
        </div>
    </div>

    <h5 class="border-bottom my-3 py-2">{{ question.answer_set | length }} - answers </h5>

    {% for answer in question.answer_set %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">
                {{ answer.content }}
            </div>
            <div class="d-flex justify-content-end">
                {% if answer.modify_date %}
                <div class="badge badge-light p-2 text-left mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ answer.modify_date | datetime }}</div>
                </div>
                {% endif %}
                <div class="badge badge-light p-2 text-left">
                    <div class="mb-2">
                        {{ answer.user.username }}
                    </div>
                    <div>
                        {{ answer.create_day | datetime }}
                    </div>
                </div>
            </div>
            {% if g.user == answer.user %}
            <div class="my-3">
                <a href="{{ url_for('answer.modify', answer_id=answer.id) }}" class="btn btn-sm btn-outline-secondary">addvvvise</a>
                <a href="#" class="delete btn btn-sm btn-outline-secondary" data-uri="{{ url_for('answer.delete', answer_id=answer.id) }}">deeelete</a>
            </div>
            {% endif %}
        </div>
    </div>
    {% endfor %}

    <form action="{{ url_for('answer.create', question_id=question.id) }}" method="post" class="my-3">

        {{ form.csrf_token }}

        {% for field, errors in form.errors.items() %}
        <div class="alert alert-danger" role="alert">
            <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
        </div>
        {% endfor %}

        <div class="form-group">
            <textarea {% if not g.user %}disabled{% endif %} name="content" id="content" class="form-control" rows="8"></textarea>
        </div>
        <input type="submit" value="답변등록">
    </form>

</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
    $(document).ready(function () {
        $(".delete").on('click', function () {
            if (confirm("reeaaaly?")) {
                location.href = $(this).data('uri');
            }
        });
    });
</script>
{% endblock %}

pybo/templates/question/question_form.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문 등록</h5>
    <form method="post" class="post-form my-3">
        {{ form.csrf_token }}

        {% for field, errors in form.errors.items() %}
        <div class="alert alert-danger" role="alert">
            <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
        </div>
        {% endfor %}

        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject" value="{{ form.subject.data or '' }}">
        </div>

        <div class="form-group">
            <label for="content">내용</label>
            
            <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.data or '' }}</textarea>
          
           
            
        </div>

        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>

{% endblock %}

{% block script %}

{% endblock %}

pybo/templates/question/question_list.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-3">
    <table class="table">
        <thead>
            <tr class="text-center thead-dark">
                <th>no.</th>
                <th style="width:50">title</th>
                <th>writer</th>
                <th>date</th>
            </tr>
        </thead>

        <tbody>
            {% if question_list %}
            {% for question in question_list.items %}
            <tr class="text-center">
                <td>{{ question_list.total - ((question_list.page - 1) * question_list.per_page) - loop.index0 }}</td>
                <td class="text-left">
                    <a href="{{ url_for('question.detail', question_id=question.id) }}">{{ question.subject }}</a>
                    {% if question.answer_set | length > 0 %}
                    <span class="text-danger small ml-2">{{ question.answer_set | length }}</span>
                    {% endif %}
                </td>
                <td>{{ question.user.username }}</td>
                <td>{{ question.create_day | datetime }}</td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="3">no questinos</td>
            </tr>
            {% endif %}
        </tbody>
    </table>

    <ul class="pagination justify-content-center">

        {% if question_list.has_prev %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.prev_num }}">ppprev</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">PREV</a>
        </li>
        {% endif %}



        {% for page_num in question_list.iter_pages() %}
        {% if page_num %}
        {% if page_num != question_list.page %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
        </li>
        {% else %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="#">{{ page_num }}</a>
        </li>
        {% endif %}
        {% else %}
        <li class="disabled">
            <a class="page-link" href="#">...</a>
        </li>
        {% endif %}
        {% endfor %}


        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.next_num }}">nnnext</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">NEXT</a>
        </li>
        {% endif %}

    </ul>




    <a href="{{ url_for('question.create') }}" class="btn btn-primary">질문 등로오오오록</a>

</div>
{% endblock %}